# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "pr: github-actions"

  - package-ecosystem: npm
    directory: "/"
    versioning-strategy: increase
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
        update-types:
          - "minor"
          - "patch"
      react:
        patterns:
          - "react"
          - "react-dom"
        update-types:
          - "minor"
          - "patch"
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
      semver-minor-days: 4
      semver-patch-days: 4
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "pr: pnpm-dependencies"
