overrides:
  "serialize-javascript": "^7.0.5"
  "brace-expansion": "^5.0.9"
  "fast-uri": "^3.1.5"
  "uuid": "^11.1.1"

minimumReleaseAge: 10080 # 7 days in minutes
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeExclude:
  - pnpm
  - brace-expansion@5.0.9

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 525600 # ignore packages published 1+ year ago
trustPolicyExclude:
  - 'detect-port@1.6.1'
  - 'semver@6.3.1'

trustLockfile: false
blockExoticSubdeps: true
verifyDepsBeforeRun: error

strictDepBuilds: true
dangerouslyAllowAllBuilds: false
allowBuilds:
  '@swc/core': true
  core-js-pure: true
  core-js: true
