name: Test deployment

on:
  pull_request:
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: pnpm/setup@v2.0.0
        with:
          install: false
      - run: pnpm install --frozen-lockfile
      
      - name: Test build website
        run: pnpm run build
